### ISSUE TITLE
Not suitable for smartphone

### ISSUE THREAD

**Issue by Li-An** [natata7/mixtape#1]
Hello, I’ve used Mistape plugin before it stopped working and I’m glad to see this new Mixtape but it lacks the same functonnality than Mistape : an user browsing from a smartphone or tablet cannot type Ctrl+Enter. Reword plugin gives a nice solution but I don’t know if it is possible in Mixtape.

**Comment by natata7** [comment]
Hello, thank you for your helpful comment.This feature will be added soon.

**Comment by Li-An** [comment]
That’s interersting. Curious to see how you will manage this. I plan to translate your plugin in French - if I found some time.

**Comment by natata7** [comment]
Hello, I added compatibility of the plugin with smartphones. I will also be very grateful for your help with the translation. It is really helpful.
I currently mark the issue as resolved
